apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterresourceoverride-anonymous-access
rules:
  - apiGroups:
      - "admission.autoscaling.openshift.io"
    resources:
      - "clusterresourceoverrides"
    verbs:
      - create
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clusterresourceoverride-anonymous-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clusterresourceoverride-anonymous-access
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: system:anonymous
