apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: clusterresourceoverride-scc-hostnetwork-use
  namespace: cluster-resource-override
rules:
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    verbs:
      - use
    resourceNames:
      - hostnetwork
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: clusterresourceoverride-scc-hostnetwork-use
  namespace: cluster-resource-override
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: clusterresourceoverride-scc-hostnetwork-use
subjects:
  - kind: ServiceAccount
    namespace: cluster-resource-override
    name: clusterresourceoverride
